Repository Requisitos-de-Software/2025.1-Cadastro-Unico, pull requests merged in 2025-05, with the labels that each got.

#63 Docs/inspecao-1
  docs/inspecoes/grupo+1/inspecao_1.md
  docs/inspecoes/grupo/inspecao_1.md
  docs/verificacao/grupo+1/checklist_1.md
  docs/verificacao/grupo/checklist_1.md
Labels: documentation

#75 Docs: Atualizando técnica Three Level Scale
  docs/elicitacao/entrevista.md
  docs/priorizacao/three_level_scale.md
Labels: documentation

#76 Docs/priorização/first-things-first
  docs/assets/diagrama-ftf.jpg
  docs/priorizacao/first_thing_first.md
Labels: documentation

#81 Docs/priorizacao 100
  docs/elicitacao/perfil_usuario.md
  docs/elicitacao/priorizacao/100dollars.md
  mkdocs.yml
Labels: documentation

#79 Docs/cronograma exec2
  docs/planejamento/cronograma_executado.md
Labels: documentation

#86 Docs/lista de verificacao 2
  docs/assets/verificacao2/fonte1.png
  docs/assets/verificacao2/fonte2.png
  docs/assets/verificacao2/fonte3.png
  docs/assets/verificacao2/fonte4.png
  docs/assets/verificacao2/fonte5.png
  docs/assets/verificacao2/fonte6.png
  docs/assets/verificacao2/fonte7.png
  docs/inspecoes/grupo+1/inspecao_1.md
  docs/inspecoes/grupo/inspecao_1.md
  docs/verificacao/checklist_1.md
  docs/verificacao/checklist_2.md
  docs/verificacao/grupo+1/checklist_1.md
  mkdocs.yml
Labels: documentation

#87 docs: adicionando a inspeção do grupo+1
  docs/inspecoes/grupo+1/inspecao_2.md
  mkdocs.yml
Labels: documentation

#88 docs: ajustes na documentação e mkdocs
  README.md
  docs/assets/css/custom.css
  docs/assets/referencias/analise_documentacao/analise_documentacao.png
  docs/assets/referencias/analise_documentacao/analise_documentacao1.png
  docs/assets/referencias/analise_documentacao/analise_documentacao10.png
  docs/assets/referencias/analise_documentacao/analise_documentacao11.png
  docs/assets/referencias/analise_documentacao/analise_documentacao12.png
  docs/assets/referencias/analise_documentacao/analise_documentacao13.png
  docs/assets/referencias/analise_documentacao/analise_documentacao14.png
  docs/assets/referencias/analise_documentacao/analise_documentacao2.png
  docs/assets/referencias/analise_documentacao/analise_documentacao3.png
  docs/assets/referencias/analise_documentacao/analise_documentacao4.png
  docs/assets/referencias/analise_documentacao/analise_documentacao5.png
  docs/assets/referencias/analise_documentacao/analise_documentacao6.png
  docs/assets/referencias/analise_documentacao/analise_documentacao7.png
  docs/assets/referencias/analise_documentacao/analise_documentacao8.png
  docs/assets/referencias/analise_documentacao/analise_documentacao9.png
  docs/assets/referencias/entrevista/Start.md
  docs/assets/referencias/introspeccao/introspeccao1.png
  docs/assets/referencias/introspeccao/introspeccao2.png
  docs/assets/referencias/questionario/Start.md
  docs/assets/referencias/three_level_scale/three_level_scale1.png
  docs/assets/referencias/three_level_scale/three_level_scale2.png
  docs/atas/tecnicas/reuniaoElicitacao1.md
  docs/atas/tecnicas/reuniaoElicitacao2.md
  docs/elicitacao/perfil_usuario.md
  docs/elicitacao/priorizacao/three_level_scale.md
  docs/elicitacao/tecnicas/analise_documentacao.md
  docs/elicitacao/tecnicas/entrevista.md
  docs/elicitacao/tecnicas/introspecção.md
  docs/inspecoes/grupo+1/inspecao_1.md
  mkdocs.yml
Labels: documentation

#91 Docs: Adicionando introdução do novo conteúdo
  docs/assets/referencias/introducao_cenario/introducao_cenario_caso_de_uso.png
  docs/assets/referencias/introducao_cenario/introducao_cenario_cenario.png
  docs/cenarios/introducao.md
  mkdocs.yml
Labels: documentation

#100 Docs/modelagem/cenarios
  docs/assets/referencias/introducao_cenario/introducao_modelagem.png
  docs/elicitacao/requisitos_elicitados.md
  docs/modelagem/cenarios.md
  docs/modelagem/introducao.md
  docs/planejamento/cronograma_executado.md
Labels: documentation

#94 Modelagem de Requisitos - Léxico
  docs/assets/referencias/modelagem/RefCasosDeUso.png
  docs/assets/referencias/modelagem/RefCen.png
  docs/assets/referencias/modelagem/RefEspSup.png
  docs/assets/referencias/modelagem/RefLex.png
  docs/assets/referencias/modelagem/RefTabLex.png
  docs/elicitacao/priorizacao/introducao.md
  docs/modelagem/introducao.md
  docs/modelagem/lexico.md
Labels: documentation

#104 docs: adicionando correção de cenario
  docs/modelagem/cenarios.md
Labels: documentation

#109 docs: adicionando cenários faltantes
  docs/modelagem/cenarios.md
Labels: documentation

#107 Docs/lista de verificacao
  docs/assets/verificacao3/Checklist_CU.pdf
  docs/assets/verificacao3/Checklist_Cenarios.pdf
  docs/assets/verificacao3/Checklist_ES.pdf
  docs/assets/verificacao3/fonte1.png
  docs/assets/verificacao3/fonte2.png
  docs/assets/verificacao3/fonte3.png
  docs/assets/verificacao3/fonte4.png
  docs/verificacao/checklist_3.md
  mkdocs.yml
Labels: documentation

#101 docs:especificacao_suplementar
  docs/assets/referencias/especificacao_suplementar/especificacao_suplementar.png
  docs/assets/referencias/especificacao_suplementar/especificacao_suplementar1.png
  docs/elicitacao/requisitos_elicitados.md
  docs/modelagem/especificacao_suplementar.md
  docs/modelagem/introducao.md
  mkdocs.yml
Labels: documentation, ASAP, CRITICAL

#115 Add Inspeção 3
  docs/inspecoes/grupo/inspecao_3.md
Labels: documentation

#119 Docs: Adicionando hyperlinks na tabela de elicitação
  docs/elicitacao/requisitos_elicitados.md
Labels: documentation

#118 Docs: Ajuste do lexico para compor os UC10, UC11 e UC12
  docs/modelagem/lexico.md
Labels: documentation, ASAP
