Repository Requisitos-de-Software/2025.1-Cadastro-Unico, pull requests merged in 2025-04, with the labels that each got.

#4 docs: adicionando heatmap
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/assets/heatmap.png
  docs/planejamento/heatmap.md
Labels: documentation

#11 Readme/equipe
  README.md
  docs/assets/logo-ctd.png
Labels: documentation

#9 docs: escolha do aplicativo
  docs/assets/rp-v1-actors.png
  docs/assets/rp-v1-app-escolhido.png
  docs/assets/rp-v1-arrows.png
  docs/assets/rp-v1-boundary.png
  docs/assets/rp-v1-operations.png
  docs/assets/rp-v1-tables.png
  docs/planejamento/aplicativo.md
Labels: documentation

#14 docs: adicionando ferramentas
  docs/assets/chrome.jpg
  docs/assets/docs.jpg
  docs/assets/drawio.jpg
  docs/assets/gimp.jpg
  docs/assets/git.jpg
  docs/assets/github.jpg
  docs/assets/heatmap.jpg
  docs/assets/microsoft-teams.jpg
  docs/assets/telegram.jpg
  docs/assets/visual-studio-code.jpg
  docs/planejamento/ferramentas.md
  docs/planejamento/heatmap.md
  docs/style/logo.png
Labels: documentation

#19 feat: atualizando mkdocs
  docs/index.md
  mkdocs.yml
Labels: enhancement, ASAP

#20 Atas 1-4
  docs/atas/reuniao1.md
  docs/atas/reuniao2.md
  docs/atas/reuniao3.md
  docs/atas/reuniao4.md
Labels: documentation, ASAP

#22 docs: adicionando termos de uso
  docs/assets/termos_de_uso/1.png
  docs/assets/termos_de_uso/10.png
  docs/assets/termos_de_uso/11.png
  docs/assets/termos_de_uso/12.png
  docs/assets/termos_de_uso/13.png
  docs/assets/termos_de_uso/14.png
  docs/assets/termos_de_uso/15.png
  docs/assets/termos_de_uso/16.png
  docs/assets/termos_de_uso/17.png
  docs/assets/termos_de_uso/18.png
  docs/assets/termos_de_uso/19.png
  docs/assets/termos_de_uso/2.png
  docs/assets/termos_de_uso/3.png
  docs/assets/termos_de_uso/4.png
  docs/assets/termos_de_uso/5.png
  docs/assets/termos_de_uso/6.png
  docs/assets/termos_de_uso/7.png
  docs/assets/termos_de_uso/8.png
  docs/assets/termos_de_uso/9.png
  docs/planejamento/termosDeUso.md
  mkdocs.yml
Labels: documentation, ASAP

#23 fix: imagens
  docs/planejamento/termosDeUso.md
Labels: enhancement

#27 DOCS: criado documento para a primeira inspeção
  docs/inspecoes/inspecao1.md
Labels: documentation, ASAP, CRITICAL

#30 docs: correcao-apresentacao
  README.md
  docs/assets/app-carteira.png
  docs/assets/richPictures/Amanda.jpg
  docs/assets/richPictures/Amanda.png
  docs/atas/reuniao1.md
  docs/atas/reuniao2.md
  docs/atas/reuniao3.md
  docs/atas/reuniao4.md
  docs/index.md
  docs/planejamento/cronograma.md
  docs/planejamento/cronograma_executado.md
  docs/planejamento/ferramentas.md
  docs/planejamento/heatmap.md
  docs/planejamento/metodologia.md
  docs/planejamento/termosDeUso.md
  docs/pre-rastreabilidade/aplicativo.md
  docs/pre-rastreabilidade/appsAnalisados.md
Labels: documentation

#28 Atualização cronograma.md
  docs/planejamento/cronograma.md
Labels: documentation

#44 docs: correções
  docs/planejamento/cronograma.md
Labels: documentation

#47 doc: criação e agregação da pagina index de elicitação
  docs/elicitacao/index.md
Labels: documentation

#46 Docs/introspecção
  docs/elicitacao/introspecção.md
Labels: documentation

#50 Doc: Técnica first thing first
  priorizacao/first_thing_first.md
Labels: documentation

#58 Docs/three level scale
  docs/priorizacao/first_thing_first.md
  docs/priorizacao/three_level_scale.md
Labels: documentation

#61 docs: atualizando termos de uso
  docs/assets/termos_de_uso/1.png
  docs/assets/termos_de_uso/10.png
  docs/assets/termos_de_uso/11.png
  docs/assets/termos_de_uso/12.png
  docs/assets/termos_de_uso/13.png
  docs/assets/termos_de_uso/14.png
  docs/assets/termos_de_uso/15.png
  docs/assets/termos_de_uso/16.png
  docs/assets/termos_de_uso/17.png
  docs/assets/termos_de_uso/18.png
  docs/assets/termos_de_uso/19.png
  docs/assets/termos_de_uso/2.png
  docs/assets/termos_de_uso/3.png
  docs/assets/termos_de_uso/4.png
  docs/assets/termos_de_uso/5.png
  docs/assets/termos_de_uso/6.png
  docs/assets/termos_de_uso/7.png
  docs/assets/termos_de_uso/8.png
  docs/assets/termos_de_uso/9.png
  docs/planejamento/termosDeUso.md
Labels: documentation
